import factory from '@adonisjs/lucid/factories'
import Entry from '#models/entry'
import { DateTime } from 'luxon'

export const EntryFactory = factory
  .define(Entry, async ({ faker }) => {
    const entryTypes = ['daily', 'til', 'snippet', 'debug', 'achievement']
    const entryType = faker.helpers.arrayElement(entryTypes)

    // Generate content based on entry type
    const { title, content } = generateContentForType(entryType, faker)

    return {
      entryType,
      title,
      contentMarkdown: content,
      // contentHtml and contentPlain will be generated by the beforeSave hook
      metadata: generateMetadataForType(entryType, faker),
      createdAt: DateTime.fromJSDate(
        faker.date.between({
          from: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000), // 90 days ago
          to: new Date(),
        })
      ),
    }
  })
  .state('daily', (entry, { faker }) => {
    const { title, content } = generateContentForType('daily', faker)
    entry.merge({
      entryType: 'daily',
      title,
      contentMarkdown: content,
      metadata: generateMetadataForType('daily', faker),
    })
  })
  .state('til', (entry, { faker }) => {
    const { title, content } = generateContentForType('til', faker)
    entry.merge({
      entryType: 'til',
      title,
      contentMarkdown: content,
      metadata: generateMetadataForType('til', faker),
    })
  })
  .state('snippet', (entry, { faker }) => {
    const { title, content } = generateContentForType('snippet', faker)
    entry.merge({
      entryType: 'snippet',
      title,
      contentMarkdown: content,
      metadata: generateMetadataForType('snippet', faker),
    })
  })
  .state('debug', (entry, { faker }) => {
    const { title, content } = generateContentForType('debug', faker)
    entry.merge({
      entryType: 'debug',
      title,
      contentMarkdown: content,
      metadata: generateMetadataForType('debug', faker),
    })
  })
  .state('achievement', (entry, { faker }) => {
    const { title, content } = generateContentForType('achievement', faker)
    entry.merge({
      entryType: 'achievement',
      title,
      contentMarkdown: content,
      metadata: generateMetadataForType('achievement', faker),
    })
  })
  .build()

function generateContentForType(entryType: string, faker: any): { title: string; content: string } {
  const date = DateTime.now().toISODate()

  switch (entryType) {
    case 'daily':
      return {
        title: `Daily Log - ${date}`,
        content: generateDailyContent(faker),
      }

    case 'til':
      const tilTopics = [
        'React Hooks optimization',
        'PostgreSQL window functions',
        'Docker multi-stage builds',
        'TypeScript utility types',
        'Node.js streams',
        'CSS Grid advanced techniques',
        'Git rebase vs merge',
        'API rate limiting strategies',
        'Database indexing best practices',
        'JavaScript closures deep dive',
      ]
      return {
        title: `TIL: ${faker.helpers.arrayElement(tilTopics)}`,
        content: generateTilContent(faker),
      }

    case 'snippet':
      const snippetTitles = [
        'Async error handling utility',
        'Custom React hook for API calls',
        'Database connection pool setup',
        'JWT token validation middleware',
        'File upload with progress tracking',
        'Debounce function implementation',
        'CSS flexbox centering trick',
        'SQL query optimization',
        'Environment config loader',
        'API response formatter',
      ]
      return {
        title: faker.helpers.arrayElement(snippetTitles),
        content: generateSnippetContent(faker),
      }

    case 'debug':
      const debugTitles = [
        'Memory leak in React component',
        'Database connection timeout',
        'CORS issues with API calls',
        'Performance bottleneck in query',
        'Authentication middleware bug',
        'File upload size limit error',
        'CSS layout breaking on mobile',
        'Race condition in async code',
        'Docker container startup failure',
        'TypeScript compilation errors',
      ]
      return {
        title: faker.helpers.arrayElement(debugTitles),
        content: generateDebugContent(faker),
      }

    case 'achievement':
      const achievementTitles = [
        'Completed React certification',
        'Deployed first microservice',
        'Reduced API response time by 50%',
        'Mentored junior developer',
        'Contributed to open source project',
        'Implemented CI/CD pipeline',
        'Optimized database queries',
        'Led technical architecture review',
        'Presented at team tech talk',
        'Completed performance optimization project',
      ]
      return {
        title: faker.helpers.arrayElement(achievementTitles),
        content: generateAchievementContent(faker),
      }

    default:
      return {
        title: 'Untitled Entry',
        content: faker.lorem.paragraphs(2),
      }
  }
}

function generateDailyContent(faker: any): string {
  const activities = [
    'Worked on user authentication feature',
    'Fixed bug in payment processing',
    'Reviewed pull requests from team',
    'Attended sprint planning meeting',
    'Refactored legacy code',
    'Implemented new API endpoint',
    'Updated documentation',
    'Debugged production issue',
    'Optimized database queries',
    'Set up monitoring alerts',
  ]

  const blockers = [
    'Waiting for API documentation',
    'Need design approval for UI changes',
    'Database migration pending',
    'Third-party service downtime',
    'Unclear requirements',
    'Missing test data',
    'Environment setup issues',
    'Code review feedback pending',
  ]

  return `# Daily Log

## What I did today
- ${faker.helpers.arrayElement(activities)}
- ${faker.helpers.arrayElement(activities)}
- ${faker.helpers.arrayElement(activities)}

## What's next
- ${faker.lorem.sentence()}
- ${faker.lorem.sentence()}

## Blockers/Issues
- ${faker.helpers.arrayElement(blockers)}

## Notes
${faker.lorem.paragraph()}`
}

function generateTilContent(faker: any): string {
  const technologies = ['React', 'Node.js', 'PostgreSQL', 'TypeScript', 'Docker', 'AWS', 'GraphQL']
  const tech = faker.helpers.arrayElement(technologies)

  return `# Today I Learned: ${tech}

## What I learned
${faker.lorem.paragraphs(2)}

## Resources/Links
- [${faker.lorem.words(3)}](${faker.internet.url()})
- [${faker.lorem.words(4)}](${faker.internet.url()})

## Code example
\`\`\`javascript
// ${faker.lorem.sentence()}
const example = {
  ${faker.lorem.word()}: '${faker.lorem.words(2)}',
  ${faker.lorem.word()}: ${faker.number.int({ min: 1, max: 100 })}
};

console.log(example);
\`\`\`

## Key takeaways
${faker.lorem.paragraph()}`
}

function generateSnippetContent(faker: any): string {
  const languages = ['javascript', 'typescript', 'python', 'sql', 'bash']
  const language = faker.helpers.arrayElement(languages)

  const codeExamples: Record<string, string> = {
    javascript: `function ${faker.lorem.word()}(${faker.lorem.word()}) {
  return ${faker.lorem.word()}.map(item => ({
    ...item,
    ${faker.lorem.word()}: item.${faker.lorem.word()}.toUpperCase()
  }));
}`,
    typescript: `interface ${faker.lorem.word().charAt(0).toUpperCase() + faker.lorem.word().slice(1)} {
  ${faker.lorem.word()}: string;
  ${faker.lorem.word()}: number;
}

const ${faker.lorem.word()}: ${faker.lorem.word().charAt(0).toUpperCase() + faker.lorem.word().slice(1)} = {
  ${faker.lorem.word()}: '${faker.lorem.words(2)}',
  ${faker.lorem.word()}: ${faker.number.int({ min: 1, max: 100 })}
};`,
    python: `def ${faker.lorem.word()}(${faker.lorem.word()}):
    """${faker.lorem.sentence()}"""
    return [item.${faker.lorem.word()}() for item in ${faker.lorem.word()}]`,
    sql: `SELECT ${faker.lorem.word()}, COUNT(*) as total
FROM ${faker.lorem.word()}
WHERE ${faker.lorem.word()} > '${faker.date.recent().toISOString().split('T')[0]}'
GROUP BY ${faker.lorem.word()}
ORDER BY total DESC;`,
    bash: `#!/bin/bash
${faker.lorem.word().toUpperCase()}="${faker.lorem.words(2)}"
for file in *.${faker.lorem.word()}; do
  echo "Processing $file"
done`,
  }

  return `# ${faker.lorem.words(3)}

## Language/Technology
${language}

## Problem it solves
${faker.lorem.paragraph()}

## Code
\`\`\`${language}
${codeExamples[language] || codeExamples.javascript}
\`\`\`

## Explanation
${faker.lorem.paragraphs(2)}

## Usage
${faker.lorem.paragraph()}`
}

function generateDebugContent(faker: any): string {
  const timeSpent = faker.helpers.arrayElement([
    '30 minutes',
    '1 hour',
    '2 hours',
    '3 hours',
    'Half day',
  ])

  return `# ${faker.lorem.words(4)}

## Problem description
${faker.lorem.paragraphs(2)}

## What I tried
- ${faker.lorem.sentence()}
- ${faker.lorem.sentence()}
- ${faker.lorem.sentence()}

## Solution
${faker.lorem.paragraphs(2)}

## Time spent
${timeSpent}

## Lessons learned
${faker.lorem.paragraph()}

## Prevention
${faker.lorem.paragraph()}`
}

function generateAchievementContent(faker: any): string {
  const technologies = [
    'React',
    'Node.js',
    'PostgreSQL',
    'TypeScript',
    'Docker',
    'AWS',
    'GraphQL',
    'Python',
  ]
  const techStack = faker.helpers.arrayElements(technologies, { min: 2, max: 4 })

  return `# ${faker.lorem.words(4)}

## What I accomplished
${faker.lorem.paragraphs(2)}

## Impact/Results
- ${faker.lorem.sentence()}
- ${faker.lorem.sentence()}
- ${faker.lorem.sentence()}

## Technologies used
${techStack.map((tech: string) => `- ${tech}`).join('\n')}

## Challenges overcome
${faker.lorem.paragraph()}

## What I learned
${faker.lorem.paragraph()}

## Next steps
${faker.lorem.paragraph()}`
}

function generateMetadataForType(entryType: string, faker: any): Record<string, any> {
  switch (entryType) {
    case 'debug':
      return {
        timeSpent: faker.helpers.arrayElement(['30m', '1h', '2h', '3h', '4h']),
        severity: faker.helpers.arrayElement(['low', 'medium', 'high', 'critical']),
        resolved: faker.datatype.boolean(),
      }

    case 'snippet':
      return {
        language: faker.helpers.arrayElement(['javascript', 'typescript', 'python', 'sql', 'bash']),
        complexity: faker.helpers.arrayElement(['beginner', 'intermediate', 'advanced']),
      }

    case 'achievement':
      return {
        category: faker.helpers.arrayElement(['learning', 'project', 'career', 'contribution']),
        impact: faker.helpers.arrayElement(['personal', 'team', 'company', 'community']),
      }

    case 'til':
      return {
        source: faker.helpers.arrayElement([
          'documentation',
          'tutorial',
          'course',
          'colleague',
          'experimentation',
        ]),
        difficulty: faker.helpers.arrayElement(['easy', 'medium', 'hard']),
      }

    default:
      return {}
  }
}
